version: "3.9"

services:
  library_db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: gces
      POSTGRES_USER: gces
      POSTGRES_DB: library_db

  library_back:
    build: ./library_back/
    environment:
      POSTGRES_PASSWORD: gces
      POSTGRES_USER: gces
      POSTGRES_DB: library_db
      POSTGRES_HOST: library_db
      POSTGRES_PORT: 5432
    volumes:
      - ./library_back:/home/library_back
    ports:
      - 8000:8000
    depends_on:
      - library_db
    entrypoint: 
      ./start.sh

  library_front:
    build: ./library_front/
    volumes:
      - ./library_front:/home/library_front
      - /home/library_front/node_modules
    ports:
      - 3000:3000
    entrypoint:
      npm start