version: "3.9"

services:
  library_db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: gces
      POSTGRES_USER: gces
      POSTGRES_DB: library_db
    networks:
      gces-trabalho-individual:
        aliases:
          - library_db

  library_back:
    build: ./library_back/
    image: thiagohdaqw/library_back
    restart: always
    environment:
      POSTGRES_PASSWORD: gces
      POSTGRES_USER: gces
      POSTGRES_DB: library_db
      POSTGRES_HOST: library_db
      POSTGRES_PORT: 5432
    volumes:
      - ./library_back:/home/library_back
    ports:
      - 8000:8000
    depends_on:
      - library_db
    entrypoint: 
      ./start.sh
    networks:
      gces-trabalho-individual:
        aliases:
          - library_back

  library_front:
    build: ./library_front/
    image: thiagohdaqw/library_front
    restart: always
    volumes:
      - ./library_front:/home/library_front
      - /home/library_front/node_modules
    ports:
      - 3000:3000
    entrypoint:
      npm start
    depends_on:
      - library_back
    networks:
      gces-trabalho-individual:
        aliases:
          - library_front

  library_nginx:
    build: ./nginx/
    image: thiagohdaqw/library_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - library_front
    networks:
      gces-trabalho-individual:
        aliases:
          - library_nginx

networks:
  gces-trabalho-individual: