name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Images
        run: make build

      - name: Test backend
        run: make test-back

      - name: Test frontend
        run: make test-front

      - name: Lint frontend
        run: make lint-front

      - name: Lint backend
        run: make lint-back
