name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Images
        run: docker-compose build

      - name: Test backend
        run: docker-compose run --rm --entrypoint "bash test.sh" library_back

      - name: Test frontend
        run: docker-compose run --rm --no-deps --entrypoint "npm run test --ci=true --watchAll=false" library_front 

      - name: Lint frontend
        run: docker-compose run --rm --no-deps --entrypoint "npm run lint" library_front
